export const countries = [
	'United States',
	'China',
	'Japan',
	'Germany',
	'France',
	'India',
	'Italy',
	'Brazil',
	'Canada',
	'South Korea',
	'Russian Federation',
	'Spain',
	'Australia',
	'Mexico',
	'Indonesia',
	'Netherlands',
	'Saudi Arabia',
	'Türkiye',
	'Switzerland',
	'Taiwan',
	'Poland',
	'Sweden',
	'Belgium',
	'Argentina',
	'Thailand',
	'Austria',
	'Iran',
	'Norway',
	'United Arab Emirates',
	'Nigeria',
	'Ireland',
	'Israel',
	'Hong Kong',
	'Singapore',
	'South Africa',
	'Malaysia',
	'Denmark',
	'Colombia',
	'Philippines',
	'Pakistan',
	'Chile',
	'Bangladesh',
	'Finland',
	'Egypt',
	'Czechia',
	'Portugal',
	'Romania',
	'Vietnam',
	'Iraq',
	'Peru',
	'Greece',
	'New Zealand',
	'Qatar',
	'Kazakhstan',
	'Hungary',
	'Kuwait',
	'Ukraine',
	'Morocco',
	'Algeria',
	'Ecuador',
	'Slovakia',
	'Venezuela',
	'Sri Lanka',
	'Dominican Republic',
	'Ethiopia',
	'Oman',
	'Guatemala',
	'Luxembourg',
	'Angola',
	'Myanmar',
	'Bulgaria',
	'Croatia',
	'Uruguay',
	'Belarus',
	'Panama',
	'Lebanon',
	'Slovenia',
	'Macao',
	'Lithuania',
	'Serbia',
	'Democratic Republic Of Congo',
	'Azerbaijan',
	'Uzbekistan',
	"Cote D'Ivoire",
	'Jordan',
	'Bolivia',
	'Libya',
	'Costa Rica',
	'Cameroon',
	'Tunisia',
	'Bahrain',
	'Latvia',
	'Sudan',
	'Estonia',
	'Nepal',
	'Yemen',
	'Paraguay',
	'Zambia',
	'Iceland',
	'El Salvador',
	'Cyprus',
	'Cambodia',
	'Trinidad And Tobago',
	'Honduras',
	'Zimbabwe',
	'Bosnia And Herzegovina',
	'Afghanistan',
	'Botswana',
	'Laos',
	'Gabon',
	'Mali',
	'Georgia',
	'European Union',
	'Euro area',
	'Montserrat',
	'New Caledonia',
	'Sint Maarten',
	'Syrian Arab Republic',
	'Kosovo',
	'Virgin Islands, British',
	'European Union (28 countries)',
	'Euro area (19 countries)',
	'Euro area (18 countries)',
	'European Economic Area (EEA18-2004, EEA28-2006, EEA30-2013, EEA31)',
	'United Kingdom',
	'Curacao',
	'Guadeloupe',
	'Martinique',
	'Palestinian Territory',
	'Euro area (12 countries)',
	'Jamaica',
	'Papua New Guinea',
	'European Union (15 countries)',
	'Albania',
	'Malta',
	'Mozambique',
	'Benin',
	'Burkina Faso',
	'Mauritius',
	'Equatorial Guinea',
	'Brunei Darussalam',
	'Nicaragua',
	'North Macedonia',
	'Bahamas',
	'Armenia',
	'Guinea',
	'Madagascar',
	'Mongolia',
	'Republic Of Congo',
	'Moldova',
	'Chad',
	'Liechtenstein',
	'Bermuda',
	'Cuba',
	'Exchange rate v dollar',
	'Monaco',
	'Andorra',
	'France (metropolitan)',
	'Haiti',
	'Niger',
	'Kyrgyzstan',
	'Malawi',
	'Tajikistan',
	'Fiji',
	'Maldives',
	'Mauritania',
	'Montenegro',
	'Togo',
	'Barbados',
	'North American Free Trade Association',
	'OECD',
	'Organisation for Economic Co-operation and Development (OECD)',
	'South Sudan',
	'Swaziland',
	'Guyana',
	'Burundi',
	'Djibouti',
	'Liberia',
	'Suriname',
	'Aruba',
	'Cape Verde',
	'Central African Republic',
	'Lesotho',
	'Timor-Leste',
	'Bhutan',
	'Belize',
	'Saint Lucia',
	'San Marino',
	'Antigua And Barbuda',
	'Comoros',
	'Grenada',
	'Guinea-Bissau',
	'Seychelles',
	'Solomon Islands',
	'Gambia',
	'Dominica',
	'Kiribati',
	'Saint Kitts And Nevis',
	'Saint Vincent And The Grenadines',
	'Samoa',
	'Sao Tome And Principe',
	'Tonga',
	'',
	'European Union (27 countries)',
	'European Union (25 countries)',
	'European Union (without United Kingdom)',
	'Euro area (17 countries)',
	'Euro area (11 countries)',
	'Euro area (16 countries)',
	'Euro area (13 countries)',
	'Euro area (15 countries)',
	'European Free Trade Association',
	'Heard Island And Mcdonald Islands',
	'World',
	'Eritrea',
	'Åland Islands',
	'Ghana',
	'Gibraltar',
	'Kenya',
	"Korea, Democratic People'S Republic Of",
	'Cayman Islands',
	'Western Sahara',
	'Namibia',
	'Tokelau',
	'Rwanda',
	'Saint Helena',
	'Sierra Leone',
	'Somalia',
	'Turkmenistan',
	'Tanzania',
	'Uganda',
	'Bonaire, Saint Eustatius and Saba',
	'Vanuatu',
	'Wallis And Futuna',
	'European Economic Area (EU27',
	'Germany (including former GDR)',
	'European Economic Area (EU-27 plus IS, LI, NO)',
	'European Economic Area (EU-28 plus IS, LI, NO)',
	'Asian Development Fund',
	'Senegal',
]
